version: '2'

services:
  webapp:
    image: 'fteychene/docker-healthcheck-test-app'
    build: webapp
    ports:
      - 3333:3333
    depends_on:
      - monitor
  monitor:
    image: 'fteychene/docker-healthcheck-test-monitor'
    build: monitor
    environment:
      COMPOSE_PROJECT_NAME:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
